app/mathtool/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,SelectMultipleField,IntegerField
from wtforms.validators import DataRequired,Length

class QuestionsForm(FlaskForm):
    result = StringField('',validators=[Length(0,64)])
    submit = SubmitField('确认')


class ConfigForm(FlaskForm):
    isInt  = BooleanField('是否整数')
    type   = SelectMultipleField('计算类型', choices=[('1','加'),('2','减'),('3','乘'),('4','除')])
    minval = IntegerField('数值下限')
    maxval = IntegerField('数值上限')
    count  = IntegerField('题目数量')
    submit = SubmitField('确认')

app/mathtool/__init__.py
from flask import Blueprint

mathtool=Blueprint('mathtool',__name__)

from . import views

app/mathtool/views.py
from flask import render_template,redirect,session,url_for,flash,current_app,request,abort
from flask_login import login_required,current_user
from .. import db
from ..models_math import Math_paper,Math_question,Math_config
from . import mathtool
from .forms import QuestionsForm, ConfigForm
from sqlalchemy import and_

@mathtool.route('/configpaper/', methods=['GET','POST'])
@login_required
def configpaper():
    math_cof=Math_config.query.filter(Math_config.user_id==current_user.id).first()
    if not math_cof:
        math_cof=Math_config()
        math_cof.user_id=current_user.id
        db.session.add(math_cof)
        db.session.commit()
    form=ConfigForm()
    if form.validate_on_submit():
        math_cof.isInt=form.isInt.data
        math_cof.type="".join(form.type.data)
        math_cof.minval=form.minval.data
        math_cof.maxval=form.maxval.data
        math_cof.count =form.count.data
        return redirect(url_for('mathtool.configpaper'))
    form.isInt.data  = math_cof.isInt
    form.type.data   = list(math_cof.type)
    form.minval.data = math_cof.minval
    form.maxval.data = math_cof.maxval
    form.count.data  = math_cof.count 
    return render_template('mathtool/configpaper.html',form=form) 

@mathtool.route('/newpaper/', methods=['GET','POST'])
@login_required
def newpaper():
    math_cof=Math_config.query.filter(Math_config.user_id==current_user.id).first()
    if not math_cof:
        math_cof=Math_config()
        math_cof.user_id=current_user.id
        db.session.add(math_cof)
        db.session.commit()
    
    Math_paper.generate_paper(current_user,isInt=math_cof.isInt,minval=math_cof.minval,maxval=math_cof.maxval,type=math_cof.type,count=math_cof.count)
    return redirect(url_for('mathtool.listpaper'))

@mathtool.route('/listpaper/')
@login_required
def listpaper():
    page = request.args.get('page', 1, type=int)
    pagination = Math_paper.query.filter(Math_paper.user_id==current_user.id).order_by(Math_paper.id.desc()).paginate(
        page, per_page=current_app.config['FLASKY_PAPER_PER_PAGE'],
        error_out=False)
    papers = pagination.items
    return render_template('mathtool/listpaper.html', papers=papers, pagination=pagination,page=page)

@mathtool.route('/delpaper/<int:id>')
@login_required
def delpaper(id):
    page = request.args.get('page', 1, type=int)
    paper=Math_paper.query.get_or_404(id)
    db.session.query(Math_question).filter(Math_question.paper_id==paper.id).delete()
    db.session.delete(paper)
    db.session.commit()
    return redirect(url_for('mathtool.listpaper',page=page))

@mathtool.route('/startpaper/<int:pid>/<int:qid>', methods=['GET','POST'])
@login_required
def startpaper(pid,qid):
    paper=Math_paper.query.get_or_404(pid)
    if paper.score_flag :
        flash('测试已完成，不能再次测试')
        page = request.args.get('page', 1, type=int)
        return redirect(url_for('mathtool.listpaper',page=page))
    form=QuestionsForm()
    if form.validate_on_submit():
        question=Math_question.query.filter(Math_question.paper_id==pid).order_by(Math_question.id).offset(qid).first()
        question.result=form.result.data or 0
        db.session.add(question)
        db.session.commit()
        if qid==Math_paper.query.get_or_404(pid).count-1:
            paper=Math_paper.query.get_or_404(pid)
            paper.score=(100/Math_paper.query.get_or_404(pid).count)*Math_question.query.filter(and_(Math_question.paper_id==pid,Math_question.key==Math_question.result)).count()
            paper.score_flag=True
            db.session.add(paper)
            db.session.commit()
            return redirect(url_for('mathtool.listpaper'))
        return redirect(url_for('mathtool.startpaper',pid=pid,qid=qid+1))
    question=Math_question.query.filter(Math_question.paper_id==pid).order_by(Math_question.id).offset(qid).first()
    return render_template('mathtool/startpaper.html',form=form,q=question,qid=qid)

@mathtool.route('/listquestion/<int:id>')
@login_required
def listquestion(id):
    paper=Math_paper.query.get_or_404(id)
    questions=Math_question.query.filter(Math_question.paper_id==id).order_by(Math_question.id).all()
    return render_template('mathtool/listquestion.html',questions=questions,paper=paper)

app/templates/mathtool/configpaper.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - 设置{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>设置</h1>
</div>
<div class="col-md-4">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/mathtool/listpaper.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - 测试{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>测试</h1>
</div>

<div class="btn-group"><a class="btn btn-primary" href="{{ url_for('mathtool.newpaper') }}">生成测试</a></div>
<div class="btn-group"><a class="btn btn-primary" href="{{ url_for('mathtool.configpaper') }}">设置</a></div>

<table class="table table-hover followers">
    <thead><tr><th>编号</th><th>生成时间</th><th>备注</th><th>成绩</th><th>操作</th></tr></thead>
    {% for paper in papers %}
    <tr {%if loop.index%2!=1 %}class="success"{%endif%}>
    <td>
    <a href="#"> {{ paper.id }} </a>
    </td>
    <td>{{ moment(paper.timestamp).format('YYYY-MM-DD HH:mm:ss') }}</td>
    <td>{{ paper.q_args}}</td>
    <td>{{ paper.score}}</td>
    <td>
    {% if not paper.score_flag %}
    <a href="{{url_for('mathtool.startpaper',pid=paper.id,qid=0)}}"> 开始 </a>
    {% endif %}
    <a href="{{url_for('mathtool.listquestion',id=paper.id)}}"> 详情 </a>
    {% if current_user.can(Permission.ADMIN) %}
    <a href="{{url_for('mathtool.delpaper',id=paper.id,page=page)}}"> 删除 </a>
    {% endif %}
    </td>
    </tr>
    {% endfor %}
</table>

{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination,'mathtool.listpaper') }}
</div>
{% endif %}

{% endblock %}

app/templates/mathtool/listquestion.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - 清单{% endblock %}

{% block page_content %}

<h3 class="text-left col-md-6">时间：{{paper.timestamp}}</h3>
<h3 class="text-right col-md-6">成绩：{{paper.score}}</h3>
<table class="table table-hover followers">
{% for q in questions %}
<tr>
<td class="{%if not q.a %}alert alert-info{% endif %}">
{% if q.a %}{{q.a}}{% else %}
<span class="{%if q.key!=q.result %}text-danger{% endif %}"><b>{{q.result}}<b></span>
{% endif %}
</td>
<td>
{% if q.op==1   %}
<span class="glyphicon glyphicon-plus"></span>
{% elif q.op==2 %}
<span class="glyphicon glyphicon-minus"></span>
{% elif q.op==3 %}<b>*</b>
{% elif q.op==4 %}<b>/</b>
{%endif%}
</td>
<td class="{%if not q.b %}alert alert-info{% endif %}">
{% if q.b %}{{q.b}}{% else %}
<span {%if q.key!=q.result %}class="text-danger" {% endif %}><b>{{q.result}}<b></span>
{% endif %}
</td>
<td><b>=</b></td>
<td class="{%if not q.val %}alert alert-info{% endif %}">
{% if q.val %}{{q.val}}{% else %}
<span {%if q.key!=q.result %}class="text-danger" {% endif %}><b>{{q.result}}<b></span>
{% endif %}
</td>
<td>{% if q.key==q.result %}<span class="glyphicon glyphicon-ok"></span>{%else%}<span class="glyphicon glyphicon-remove"></span>{%endif%}</td>
</tr>
{% endfor %}
</table>
<div class="text-center"><a class="btn btn-primary" href="{{ url_for('mathtool.listpaper') }}">返回</a></div>
{% endblock %}

app/templates/mathtool/startpaper.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}广场 - 开始测试{% endblock %}

{% block page_content %}


<div class="page-header"><h1>开始测试</h1></div>
<div class="text-right"><h3>第{{qid+1}}题</h3></div>

<div class="col-md-12">
<form action="" method="post">
    {{form.hidden_tag()}}
    <div class="input-group input-group-lg">
    {% if q.a!=None  %}<span class="input-group-addon">{{"%g"%q.a}}</span>{% else %}
    <span class="input-group-addon">{{form.result(placeholder='请输入答案')}}</span>
    {% endif %}
    <span class="input-group-addon">
      {% if q.op==1   %}+
      {% elif q.op==2 %}-
      {% elif q.op==3 %}*
      {% elif q.op==4 %}/
      {%endif%}
    </span>
    {% if q.b!=None %}<span class="input-group-addon">{{"%g"%q.b}}</span>{% else %}
    <span class="input-group-addon">{{form.result(placeholder='请输入答案')}}</span>
    {% endif %}
    <span class="input-group-addon">=</span>
    {% if q.val!=None %}<span class="input-group-addon">{{"%g"%q.val}}</span>{% else %}
    <span class="input-group-addon">{{form.result(placeholder='请输入答案')}}</span>
    {% endif %}
    <span class="input-group-addon">{{form.submit}}</span>
    </div>
</form>
</div>

{% endblock %}