app/jobtool/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField
from wtforms.validators import DataRequired,Length

class JobForm(FlaskForm):
    jobname = StringField('名称',validators=[DataRequired(),Length(1,64)])
    args    = StringField('参数',validators=[Length(0,64)])
    year    = StringField('年',validators=[Length(0,64)],default='*')
    month   = StringField('月',validators=[Length(0,64)],default='*')
    day     = StringField('日',validators=[Length(0,64)],default='*')
    hour    = StringField('时',validators=[Length(0,64)],default='*')
    minute  = StringField('分',validators=[Length(0,64)],default='*')
    second  = StringField('秒',validators=[Length(0,64)],default='*')
    day_of_week = StringField('周',validators=[Length(0,64)],default='*')
    submit = SubmitField('添加')

app/jobtool/__init__.py
from flask import Blueprint

jobtool=Blueprint('jobtool',__name__)

from . import views

app/jobtool/views.py
from flask import render_template,redirect,session,url_for,flash,current_app,request,abort
from flask_login import login_required,current_user
from .. import db,scheduler
from ..models_job import Job
from . import jobtool
from .forms import JobForm
import datetime

@jobtool.route('/addjob/', methods=['GET','POST'])
@login_required
def addjob():
    form=JobForm()
    if form.validate_on_submit():
        job=Job()
        job.jobname=form.jobname.data
        job.args=form.args.data
        job.jobtype='start'
        job.trigger='cron'
        job.year=form.year.data
        job.month=form.month.data
        job.day=form.day.data
        job.hour=form.hour.data
        job.minute=form.minute.data
        job.second=form.second.data
        job.day_of_week=form.day_of_week.data
        db.session.add(job)
        db.session.commit()
        current_app.logger.info('添加一个启动作业，ID：{}'.format(job.id))
        Job.add_job(job.id)
        return redirect(url_for('jobtool.listjob'))
    return render_template('jobtool/addjob.html',form=form)

@jobtool.route('/listjob/')
@login_required
def listjob():
    page = request.args.get('page', 1, type=int)
    pagination = Job.query.order_by(Job.id.desc()).paginate(
        page, per_page=current_app.config['FLASKY_JOB_PER_PAGE'],
        error_out=False)
    jobs = pagination.items
    return render_template('jobtool/listjob.html', jobs=jobs, pagination=pagination)

@jobtool.route('/status/<int:id>')
@login_required
def statusjob(id):
    job=Job.query.filter(Job.id==id).first()
    if job.is_enable:
        Job.remove_job(job.id)
    else :
        Job.add_job(job.id)

    return redirect(url_for('jobtool.listjob'))

@jobtool.route('/deljob/<int:id>')
@login_required
def deljob(id):
    job=Job.query.filter(Job.id==id).first()
    if job.is_enable:
        Job.remove_job(id)
    db.session.delete(job)
    db.session.commit()
    return redirect(url_for('jobtool.listjob'))

app/templates/jobtool/addjob.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - 添加启动作业{% endblock %}
{% block page_content %}
<div><h1>添加启动作业</h1></div>
<hr>
<div><a class="btn btn-primary" href="javascript:history.go(-1)">返回</a></div>
<div style="padding:20px 0px 0px 0px;">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/jobtool/joblist.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - 作业管理{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>作业管理</h1>
</div>


<table class="table table-hover followers">
    <thead><tr><th>作业名</th><th>最后一次运行时间</th><th>操作</th></tr></thead>
    {% for job in jobs %}
    <tr {%if loop.index%2!=1 %}class="success"{%endif%}>
    <td>
    <a href="#"> {{ job.jobname }} </a>
    </td>
    <td>{{ moment(job.last_timestamp).format('L') }}</td>
    <td>
    <a href="{{ url_for('jobtool.addjob') }}"> 添加 </a>
    <a href="#"> 启用 </a>
    <a href="#"> 删除 </a>
    </td>
    </tr>
    {% endfor %}
</table>

{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination,'jobtool.joblist') }}
</div>
{% endif %}

{% endblock %}

app/templates/jobtool/listjob.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - 作业管理{% endblock %}

{% block page_content %}

<h1>作业管理</h1>
<hr>
<div class="btn-group"><a class="btn btn-primary" href="{{ url_for('jobtool.addjob') }}">添加</a></div>

<table class="table table-hover followers">
    <thead><tr><th>作业名</th><th>最后一次运行时间</th><th>状态</th><th>操作</th></tr></thead>
    {% for job in jobs %}
    <tr {%if loop.index%2!=1 %}class="success"{%endif%}>
    <td>
    <a href="#"> {{ job.jobname }} </a>
    </td>
    <td>{{ job.last_timestamp }}</td>
    <td>
    {%if job.is_enable%}有效{%else%}无效{%endif%}
    </td>
    <td>
    <a href="{{ url_for('jobtool.statusjob',id=job.id) }}"> {%if job.is_enable%}禁用{%else%}启用{%endif%} </a>
    <a href="{{ url_for('jobtool.deljob',id=job.id) }}"> 删除 </a>
    </td>
    </tr>
    {% endfor %}
</table>

{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination,'jobtool.listjob') }}
</div>
{% endif %}

{% endblock %}