app/celery/__init__.py
from flask import Blueprint

celerytool=Blueprint('celerytool',__name__)

from . import views

app/celery/views.py
from flask import render_template,redirect,session,url_for,flash,current_app,request,abort,jsonify
from flask_login import login_required,current_user
from .. import db,celery
import datetime, time, random
from .tasks import mytask
from . import celerytool
from app.models_celery import Celery_task

@celerytool.route('/newtask/')
@login_required
def newtask():
    task = Celery_task()
    task.user=current_user
    db.session.add(task)
    db.session.commit()    

    celery_task = mytask.delay(task.id)

    task.task_id=celery_task.id
    db.session.add(task)
    db.session.commit()

    return redirect(url_for('celerytool.listtask'))

@celerytool.route('/test/<task_id>')
@login_required
def test(task_id):
    t = mytask.AsyncResult(task_id)
    task_percent=0
    if t.state in ('PROGRESS','SUCCESS'):
        task_percent=round(t.info.get('current')*100/t.info.get('total'),1)
    return render_template('celery/test.html', task_id=task_id ,task_percent=task_percent)

@celerytool.route('/status/<task_id>')
@login_required
def taskstatus(task_id):
    t = mytask.AsyncResult(task_id)
    task_percent=0
    end_time = None
    if t.state in ('PROGRESS','SUCCESS'):
        task_percent = str(round(t.info.get('current')*100/t.info.get('total'),1))
    if t.state in ('SUCCESS'):
        end_time = t.info.get('end_time')
    return jsonify({
        'task_status'  : t.state,
        'task_percent' : task_percent, 
        'end_time'     : end_time
    })

@celerytool.route('/listtask/')
@login_required
def listtask():
    page = request.args.get('page', 1, type=int)
    pagination = Celery_task.query.filter(Celery_task.user_id==current_user.id).order_by(Celery_task.id.desc()).paginate(
        page, per_page=current_app.config['FLASKY_TASK_PER_PAGE'],
        error_out=False)
    tasks = pagination.items
    for task in tasks:
        if task.task_status not in ['SUCCESS','FAILURE']:
            t=mytask.AsyncResult(task.task_id)
            task.task_status=t.state
            if t.state=='PROGRESS':
                task.end_time=None
                task.task_percent=round(t.info.get('current')*100/t.info.get('total'),1)
            elif t.state=='SUCCESS':
                task.end_time=datetime.datetime.strptime(t.info.get('end_time'),'%Y-%m-%d %H:%M:%S')
                task.task_percent=round(t.info.get('current')*100/t.info.get('total'),1)
            else:
                task.end_time=None
                task.task_percent=0
            db.session.add(task)
    db.session.commit() 
    return render_template('celery/listtask.html', tasks=tasks, pagination=pagination,page=page)

app/templates/celery/listtask.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - Celery{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Celery</h1>
</div>
<div class="btn-group"><a class="btn btn-primary" href="{{ url_for('celerytool.newtask') }}">生成任务</a></div>

<table class="table table-hover followers">
    <thead><tr><th>编号</th><th>开始时间</th><th>结束时间</th><th>状态</th><th>进度</th></tr></thead>
    {% for task in tasks %}
    <tr {%if loop.index%2!=1 %}class="success"{%endif%}>
    <td>
    <div class="mymid"><a href="{{ url_for('celerytool.test',task_id=task.task_id) }}"> {{ task.id }} </a></div>
    </td>

    <td>
    <div class="mymid">{{ moment(task.start_time).format('YYYY-MM-DD HH:mm:ss') }}</div>
    </td>

    <td>
    <div id="endtime{{task.task_id}}" class="mymid">
    {% if task.end_time %}
    {{ moment(task.end_time).format('YYYY-MM-DD HH:mm:ss') }}
    {% endif %}
    </div>
    </td>

    <td><div id="status{{task.task_id}}" class="mymid">{{task.task_status}}</div></td>

    <td><div class="mymid">
        <div class="progress">
        <div id="{{ task.task_id }}" class="progress-bar progress-bar-success" role="progressbar"
         aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
         style="width:{{ task.task_percent }}%">
        {{task.task_percent}}%
        </div>
        </div>
    </div></td>
    </tr>
    {% endfor %}
</table>

<script>
setInterval(function() {
  $("div").filter(".progress-bar").each(function(){
    var id =$(this).attr('id');
    $.ajax({url:"/celery/status/"+id,success:function(result){
      var res=result.task_percent+"%"
      $("#"+id).css("width",res);
      $("#"+id).text(res)
      $("#status"+id).text(result.task_status)
      if(result.end_time != null){
        $("#endtime"+id).text(result.end_time)
      }
    }});
  });
}, 2000);
</script>

{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination,'celerytool.listtask') }}
</div>
{% endif %}

{% endblock %}

app/templates/celery/test.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}广场 - Celery{% endblock %}

{% block page_content %}

<script>
setInterval(function() {
    $.ajax({url:"/celery/status/{{ task_id }}",success:function(result){
        $("#task_percent").css("width",result.task_percent+"%")
        $("#task_percent").text(result.task_percent+"%")
    }});
}, 2000);
</script>

<div class="page-header">
    <h1>Celery</h1>
</div>
<br>
<div class="progress">
    <div id="task_percent" class="progress-bar progress-bar-success" role="progressbar"
     aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
     style="width:{{ task_percent }}%">
    {{ task_percent }}%
    </div>
</div>
<div><a class="btn btn-primary" href="{{ url_for('celerytool.listtask') }}">返回</a></div>
{% endblock %}